### ISSUE TITLE
Middleware with Action Dispatching Capabilities

### ISSUE THREAD

**Issue by claytn** [fanderzon/rust-redux#7]
## Middleware needs access to dispatch
* This could be done by giving the middleware an immutable Store reference which can then be used to call dispatch. I would prefer to give middleware a closure that calls dispatch when an action is passed to it. This way we give the user access to dispatch without handing over the entire Store.

**Comment by fanderzon** [comment]
I like the idea. The only things middleware uses on a Redux store for is `dispatch` and `getState`. As long as they get the state and access to dispatching there's no need to provice a store reference. 👍
