### ISSUE TITLE
Store's State struct needs UpdateFields method

### ISSUE THREAD

**Issue by claytn** [fanderzon/rust-redux#9]
The Store's State needs to be updated in an immutable manner
 * Inside of reducers the provided store reference should not be mutated. So, to avoid this the user needs to return a copy of an updated State struct.
              One idea for this is to force the user to have their State struct to implement a trait that contains 
              an update_fields method which would be given a State struct and update the current Store's state with the new fields.

**Comment by fanderzon** [comment]
I'm not sure I follow the logic here. Reducer's already return a new state, and to internally replace the old state, with the new state seems alright to me.

It's good if we can keep the boilerplate that the user has to write down.

**Comment by claytn** [comment]
Sorry if this wasn't clear. Basically, since the state is now within a RefCell we can't simply say `self.state = (self.reducer)(self.state, action)`. This would be changing the state variable and not its internals. So we need to set `self.state.borrow_mut()`s properties. Since we can't know all the state properties the user might have I added the update_fields trait that will help update each field within this Ref<State>. Does this make more sense?

**Comment by fanderzon** [comment]
Ah, that is our problem, not out user's problem. What I did when I was mashing on my keyboard until middleware with a store reference started to work was basically this:

#[derive(Clone, Debug)]
pub struct StateContainer<T: Clone> {
    inner_state: T,
}

And then use the StateContainer in the RefCell in the Store's state, that way the actual state is an updatable property inside the StateContainer, inside the RefCell.

**Comment by claytn** [comment]
I'll update this PR with these new changes sometime today.

**Comment by fanderzon** [comment]
👍
